apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::156527737454:role/UdacityFlaskDeployCBKubectlRole
      username: build      
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::156527737454:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1A437VXE32E9C
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-03-03T17:28:13Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:mapRoles: {}
        f:mapUsers: {}
    manager: eksctl
    operation: Update
    time: "2021-03-03T17:28:13Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1357"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: b0b4e559-dce5-400e-a5dc-c827b5303124
